language: node_js
sudo: required
node_js:
- "6.10"
before_install:
  - npm install -g aws-sam-local
before_deploy:
  - sudo pip install -r requirements.txt
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master