AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon SNS trigger that logs the message pushed to the SNS topic
Resources:
  TeamDDBTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      TableName: team-table
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  GameSimulationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: Responsible for simulating game between two teams
      MemorySize: 128
      Timeout: 3
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSGameSimTopic
      # TODO: Scope access
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TeamDDBTable
  GameRunnerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: gameRunner.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: Responsible for publishing messages to SNS topic of games that need to be simulated
      MemorySize: 128
      Timeout: 3
      Events:
        MinuteRead:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      # TODO: Scope access
      Policies: AmazonDynamoDBFullAccess
      # TODO: Does this make sense to read from this table?
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TeamDDBTable
  SNSGameSimTopic:
    Type: 'AWS::SNS::Topic'